### ISSUE TITLE
fix tree plot

### ISSUE THREAD

**Issue by nicolerg** [MoTrPAC/MotrpacRatTraining6mo#32]
`get_tree_plot_for_tissue()` returns different results when the order of the input edge list is changed, e.g., these two function calls return different plots:

```r
library(MotrpacRatTraining6mo)
library(MotrpacRatTraining6moData)

tissue_edge_sets = MotrpacRatTraining6moData::GRAPH_COMPONENTS$edge_sets

get_tree_plot_for_tissue("LIVER", 
                         edge_sets = tissue_edge_sets,
                         max_trajectories = 5)

# permute
shuffled_names = sample(names(tissue_edge_sets), size=length(tissue_edge_sets), replace=FALSE)
tissue_edge_sets2 = tissue_edge_sets[shuffled_names]

get_tree_plot_for_tissue("LIVER", 
                         edge_sets = tissue_edge_sets2,
                         max_trajectories = 5)
```

This looks like most likely a bug in `filter_edge_sets_by_trajectories()`. @david-dd-amar can you try to debug?

**Comment by nicolerg** [comment]
looping in @jyu-sm who identified the issue

**Comment by nicolerg** [comment]
It looks like a bug in `get_trajectory_sizes_from_edge_sets()`, which is called within `filter_edge_sets_by_trajectories()`.

**Comment by jyu-sm** [comment]
I looked at the function get_trajectory_sizes_from_edge_sets() and it seems to me that the algorithm used does depend on the order of the edge list. To give a very simple example, (ignoring the node sets and the min size), suppose we have a graph with 3 nodes named, 0, 1, 2 and 3 edges, 0->1, 1->2, 2->3. Based on my understanding of the algo, if we feed the algo with the list of edges: [0->1, 1->2, 2->3], then we will have the longest full path: 0->1->2->3. However, if we feed the algo with the edge list: [2->3, 0->1, 1->2], then we will get 2 longest but partial paths: 1->2->3 and 0->1->2.  So in order to use this function correctly, one needs to sort the edge list by the weeks at least. If one does not want to sort the edge list before applying the function, then inside the function, we have to sort the edges by the weeks, or use a diff algo.

**Comment by nicolerg** [comment]
I think it would be safer to use an algorithm that doesn't depend on the order of the edge list, but maybe sorting inside the function is a quick fix in the meantime. @david-dd-amar have you had a chance to look at this?
