### ISSUE TITLE
Slight troubleshooting for DA using the MotrpacTraining6mo functions

### ISSUE THREAD

**Issue by christopherjin** [MoTrPAC/MotrpacRatTraining6mo#52]
Hi Folks! I ran into a small number of items that gave me a big of trouble with running some DA while testing rn6 v rn7 -- I'm not sure if I'm utilizing the correct functions in each use case but hoping to get your thoughts:

the ```fix_covariates``` function I think should be adapted for managing 0 variance across one comparison. In particular, I believe for Spleen, all the RIN values for female samples were the same, so doing DA by sex resulted in a non-full-rank matrix for the covariates. I wasn't sure how you got around that for your DA (maybe I'm using outdated functions?)

```
 for (cov in covar) {
    male_subset <- meta[sex == "male", get(cov)]
    female_subset <- meta[sex == "female", get(cov)]
    
    unique_male_values <- length(unique(male_subset))
    unique_female_values <- length(unique(female_subset))
    if (length(unique(meta[, get(cov)])) == 1 || 
        unique_male_values == 1 ||
        unique_female_values == 1) {
      
      message(sprintf("Covariate %s is constant for one of the sexs. Removing.", cov))
      covar = covar[covar != cov]
    } else {
      if (is.numeric(meta[, get(cov)])) {
        meta[, `:=`((cov), scale(meta[, get(cov)], center = center_scale, 
                                 scale = center_scale))]
      }
    }
  } 
```

Also using the ```transcript_timewise_da``` function didn't work for me for VENACV bc all the samples in T1/2 were flagged as outliers, so the timewise for comparisons b/t week 1,2 and other timepoints threw an error. 

I'm not sure if this is an issue particularly bc they may have only came up because I was using counts matrixes loaded from outside the package. Just wanted to bring these things up in case it was helpful, and mention that the package in general was super helpful in performing additional comparisons!

**Comment by nicolerg** [comment]
Hi Chris,`fix_covariates()` should handle covariates with 0 variance (see https://github.com/MoTrPAC/MotrpacRatTraining6mo/blob/main/R/fetch_prep_data.R#LL203C1-L205C34). Can you examine the resulting non-full-rank covariates matrix to see if there are any 0-variance columns? It may be that two covariates are not linearly independent. As for VENACV, good catch. When we generated the differential analysis results for the paper, we used the tables with those outliers included and then removed the female 1w, 2w results at the end. I’ll fix this soon. On May 18, 2023, at 10:25 AM, christopherjin ***@***.***> wrote:﻿
Hi Folks! I ran into a small number of items that gave me a big of trouble with running some DA while testing rn6 v rn7 -- I'm not sure if I'm utilizing the correct functions in each use case but hoping to get your thoughts:
the fix_covariates function I think should be adapted for managing 0 variance across one comparison. In particular, I believe for Spleen, all the RIN values for female samples were the same, so doing DA by sex resulted in a non-full-rank matrix for the covariates. I wasn't sure how you got around that for your DA (maybe I'm using outdated functions?)
 for (cov in covar) {
    male_subset <- meta[sex == "male", get(cov)]
    female_subset <- meta[sex == "female", get(cov)]
    
    unique_male_values <- length(unique(male_subset))
    unique_female_values <- length(unique(female_subset))
    if (length(unique(meta[, get(cov)])) == 1 || 
        unique_male_values == 1 ||
        unique_female_values == 1) {
      
      message(sprintf("Covariate %s is constant for one of the sexs. Removing.", cov))
      covar = covar[covar != cov]
    } else {
      if (is.numeric(meta[, get(cov)])) {
        meta[, `:=`((cov), scale(meta[, get(cov)], center = center_scale, 
                                 scale = center_scale))]
      }
    }
  } 

Also using the transcript_timewise_da function didn't work for me for VENACV bc all the samples in T1/2 were flagged as outliers, so the timewise for comparisons b/t week 1,2 and other timepoints threw an error.
I'm not sure if this is an issue particularly bc they may have only came up because I was using counts matrixes loaded from outside the package. Just wanted to bring these things up in case it was helpful, and mention that the package in general was super helpful in performing additional comparisons!

**Comment by christopherjin** [comment]
I meant for fix_covariates, when comparing by sex, doesn't check if the covariates have 0 variance for each individual group. For example, if doing DA on a specific sex:
The issue I had was for, spleen the RINs were like 9.x, 10, something for Male, but all 10 for female, so the female design matrix for female DA wasn't full rank, but the fix_covariates function didn't catch that.

**Comment by nicolerg** [comment]
Thanks for the clarification! I'll follow up with a PR soon.

**Comment by nicolerg** [comment]
Hi Chris, looking back into the source code, `fix_covariates()` is already applied on a per-sex basis within the `run_deseq()` function. `transcript_timewise_da()` calls `transcript_prep_data()`, which calls `fix_covariates()` (applied to male and female covariates together). Then `transcript_timewise_da()` splits the data by sex and calls `run_deseq()` on a per-sex basis, where `run_deseq()` again calls `fix_covariates()`, this time on the sex-specific covariates. So if you run `transcript_timewise_da()`, it already handles covariates that are constant for a single sex.

I would not generally recommend running `fix_covariates()` directly if you are performing differential analysis with functions in this package. If you are using custom differential analysis functions and performing differential analysis separately in each sex, then just apply `fix_covariates()` to the sex-specific metadata. 

If you're still having issues, please provide a reproducible code snippet to help me debug. 

I fixed the other issue you reported, so `transcript_timewise_da("VENACV")` now works (v1.6.4). Thank you for using these packages and letting us know when you have issues!

**Comment by christopherjin** [comment]
Ah...my apologies there, I had to make a transcript_prep_data_rn7() function for loading rn7 and implemented the sex-specific stuff in a different way. sorry to make you check through all that when it was already implemented
